[package]
name = "jpegxr"
version = "0.1.0"
authors = ["Brion Vibber <brion@pobox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
libc = "0.2.93"

[build-dependencies]
cc = "1.0.67"
bindgen = "0.58.1"
